version: "3.9"

services:
  {{ cookiecutter.project_slug }}:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - {{ cookiecutter.project_slug }}-network
    restart:
      always

networks:
  {{ cookiecutter.project_slug }}-network:
